name: 🚀 Deploy website on push
on:
  push:
    branches: [main]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-24.04
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        local-dir: ./dist/
        server-dir: ${{ secrets.FTP_PATH }}